# =============================================================================
# openloop_validation.jl  —  Strategy A: Open-Loop Dynamic Validation
# Trollheim HPP Experimental vs. Model
#
# Method:
#   Feed the MEASURED guide vane signal tau_o(t) directly as a forcing input
#   to the HydroPowerDynamics turbine+rotor model — bypassing the governor.
#   Compare simulated omega(t), Q(t), P_mech(t) against measured values.
#
#   This tests whether the turbine + rotor model equations are correct
#   independently of the governor model.
#
# Validation window:  t = 800 s → 1200 s  (plant off → full load + early SS)
#   measured  tau_o:  0.05 → 0.91 pu  (gate ramp starts at t ≈ 850 s)
#   measured  P_elec: 0 → 128 MW
#   measured  omega:  375.3 ± 0.3 RPM (synchronous throughout)
#
# Operating point identified from steady-state window (t=1200-2400s):
#   H_ss   ≈ 384.9 m
#   Q_ss   ≈ 36.4  m3/s
#   n_ss   ≈ 375.3 RPM
#   tau_o  ≈ 0.928 pu
#   P_elec ≈ 128.3 MW
#
# Inputs:
#   ../01_preprocessing/trollheim_processed.csv
#
# Outputs:
#   images/openloop_comparison.png
# =============================================================================

using CSV, DataFrames, Statistics
using DataInterpolations
using OrdinaryDiffEq
using Plots
using Printf

# ── 1. Load preprocessed data ─────────────────────────────────────────────────
csv_path = joinpath(@__DIR__, "..", "01_preprocessing", "trollheim_processed.csv")
df       = CSV.read(csv_path, DataFrame)

# ── 2. Physical & model constants ─────────────────────────────────────────────
const rho      = 1000.0           # water density  [kg/m3]
const g_acc    = 9.81             # gravity        [m/s2]
const D_runner = 2.5              # runner diameter [m]
const ETA_GEN  = 0.985            # generator efficiency (matches preprocess)

# Turbine model parameters — fitted from measured SS data (Strategy B)
# Generated by: 03_parameter_fitting/fit_turbine_params.jl
const K_q      = 0.319521         # flow coefficient  (fitted)
const eta_max  = 0.948541         # peak hydraulic efficiency  (fitted)
const c_eta    = 2.98336          # parabolic hill width coefficient  (fitted)
const Q_rated  = 36.36            # rated flow [m3/s]  (mean SS Q, fitted)

# Rotor inertia: M_a = 8 s -> J = M_a * P_rated / omega_ref^2
const omega_ref = 2π * 375.0 / 60.0   # 375 RPM in rad/s
const P_rated   = 130.6e6             # ≈ 130 MW (OP-B)
const J         = 8.0 * P_rated / omega_ref^2   # ≈ 6.74e5 kg·m²
const b_v       = 50.0                # viscous damping [N·m·s/rad]

println("=== Strategy A: Open-Loop Validation ===")
@printf "  Window       : t = 800 s -> 1200 s\n"
@printf "  K_q          = %.4f  (OP-B design)\n" K_q
@printf "  eta_max      = %.3f\n" eta_max
@printf "  J_rotor      = %.3e  kg·m²\n" J
println()

# ── 3. Extract validation window ──────────────────────────────────────────────
const T_START = 800.0
const T_END   = 1200.0

win = filter(row -> T_START <= row.t <= T_END, df)

t_abs     = Float64.(win.t)
t0        = t_abs[1]
t_rel     = t_abs .- t0           # time from window start [s]

tau_o_meas  = Float64.(win.tau_o)
H_meas      = Float64.(win.H)
Q_meas      = Float64.(win.Q)
omega_meas  = Float64.(win.omega)
n_meas      = Float64.(win.n_rpm)
P_mech_meas = Float64.(win.P_mech)

# ── 4. Forcing interpolations (tau_o, H, generator load) ──────────────────────
itp_tau_o  = LinearInterpolation(tau_o_meas,  t_rel)
itp_H      = LinearInterpolation(H_meas,      t_rel)
itp_P_mech = LinearInterpolation(P_mech_meas, t_rel)

# ── 5. Algebraic model prediction (FA.1 + FA.2 + FA.3) ────────────────────────
# These do NOT require an ODE — pure steady-state turbine equations.
Q_model      = @. tau_o_meas * K_q * D_runner^2 * sqrt(max(H_meas, 1.0))
eta_model    = @. eta_max * (1.0 - c_eta * (Q_model / Q_rated - 1.0)^2)
P_mech_model = @. rho * g_acc * Q_model * H_meas * eta_model

# ── 6. Rotor ODE: J·dω/dt = τ_turb(tau_o,H,ω) − τ_gen(P_mech_meas,ω) − b·ω ──
function rotor_ode!(du, u, p, time)
    ω        = max(u[1], 1.0)
    tau_o_v  = itp_tau_o(time)
    H_v      = max(itp_H(time), 1.0)
    P_load_v = itp_P_mech(time)               # measured generator load [W]

    Q_v      = tau_o_v * K_q * D_runner^2 * sqrt(H_v)
    eta_v    = eta_max * (1.0 - c_eta * (Q_v / Q_rated - 1.0)^2)
    P_mech_v = rho * g_acc * Q_v * H_v * eta_v

    tau_turb = P_mech_v / ω
    tau_gen  = P_load_v / ω

    du[1] = (tau_turb - tau_gen - b_v * ω) / J
end

prob     = ODEProblem(rotor_ode!, [omega_meas[1]], (t_rel[1], t_rel[end]))
sol      = solve(prob, Rodas5P(), abstol = 1e-6, reltol = 1e-6,
                 tstops = collect(0.0:1.0:t_rel[end]))

omega_sim = [sol(tt)[1] for tt in t_rel]
n_sim     = omega_sim .* 60.0 ./ (2π)

# ── 7. RMSE report ────────────────────────────────────────────────────────────
rmse_Q = sqrt(mean((Q_model     .- Q_meas).^2))
rmse_P = sqrt(mean((P_mech_model .- P_mech_meas).^2)) / 1e6
rmse_n = sqrt(mean((n_sim       .- n_meas).^2))

println("RMSE (FA.1)  Q      = $(round(rmse_Q, sigdigits=3)) m3/s")
println("RMSE (FA.3)  P_mech = $(round(rmse_P, sigdigits=3)) MW")
println("RMSE (ODE)   speed  = $(round(rmse_n, sigdigits=3)) RPM")
println()
@printf "Mean K_q check: Q_ss_model = %.2f m3/s  vs  Q_ss_meas = %.2f m3/s\n" mean(Q_model[end-100:end]) mean(Q_meas[end-100:end])

# ── 8. Comparison plot ────────────────────────────────────────────────────────
p_tau = plot(t_abs, tau_o_meas;
             label = "Measured (input)", color = :black, lw = 1.5,
             ylabel = "Gate  [pu]",
             title  = "Strategy A — Open-Loop Validation  |  Trollheim HPP")

p_q = plot(t_abs, Q_meas;
           label = "Measured",   color = :black, lw = 1.5, ls = :dash,
           ylabel = "Q  [m3/s]")
plot!(p_q,  t_abs, Q_model;
      label = "FA.1 model  (K_q=$(round(K_q, sigdigits=4)))",
      color = :steelblue, lw = 1.5)

p_p = plot(t_abs, P_mech_meas ./ 1e6;
           label = "Measured", color = :black, lw = 1.5, ls = :dash,
           ylabel = "P_mech  [MW]")
plot!(p_p,  t_abs, P_mech_model ./ 1e6;
      label = "FA.3 model",
      color = :steelblue, lw = 1.5)

p_n = plot(t_abs, n_meas;
           label = "Measured",  color = :black, lw = 1.5, ls = :dash,
           ylabel = "Speed  [RPM]")
plot!(p_n,  t_abs, n_sim;
      label = "ODE model",
      color = :steelblue, lw = 1.5)

ptop = plot(p_tau, p_q, p_p, p_n;
            layout       = (4, 1),
            size         = (900, 1000),
            link         = :x,
            legend       = :topleft,
            xlabel       = "Time  [s]",
            left_margin  = 8Plots.mm,
            bottom_margin = 3Plots.mm)

mkpath(joinpath(@__DIR__, "images"))
out_png = joinpath(@__DIR__, "images", "openloop_comparison.png")
savefig(ptop, out_png)
println("Plot saved -> 02_openloop_validation/images/openloop_comparison.png")
